### ISSUE TITLE
Husteblume API timeout

### ISSUE THREAD

**Issue by dennis3484** [artspb/homeassistant-tk-husteblume#67]
## Version of the custom_component

v0.0.8

## Log

```yaml
This error originated from a custom integration.

Logger: custom_components.tk_husteblume
Source: custom_components/tk_husteblume/api.py:82
integration: TK Husteblume (documentation, issues)
First occurred: 09:53:54 (1 occurrences)
Last logged: 09:53:54

Timeout error fetching information from https://api.husteblume-app.de/forecast/DEFRAN -
```

## Describe the bug

The Husteblume API seems to be down, resulting in the integration to stop working. The Husteblume app (on iOS) also does not work anymore and just shows a white page after opening.

A quick `curl` to the API:

```
> dhohmann # curl --connect-timeout 5 -I https://api.husteblume-app.de/forecast/DEFRAN
curl: (28) Failed to connect to api.husteblume-app.de port 443 after 5003 ms: Timeout was reached
```
